### ISSUE TITLE
Printing the interface

### ISSUE THREAD

**Issue by tuttyfrutyee** [mle-infrastructure/mle-logging#1]
Hi, how could we print out the nice interface, which initially shows up when the log object is initiated, without updating anything? Thanks...

**Comment by RobertTLange** [comment]
Hi @tuttyfrutyee! If I understand you correctly, you mean the startup info with the banner and the general logging info? Have a look at the second cell of the [example notebook](https://github.com/RobertTLange/mle-logging/blob/main/examples/getting_started.ipynb):

```python
# Instantiate logging to experiment_dir
log = MLELogger(time_to_track=['num_updates', 'num_epochs'],
                what_to_track=['train_loss', 'test_loss'],
                experiment_dir="experiment_dir/",
                use_tboard=True,
                model_type='torch',
                print_every_k_updates=1,
                verbose=True)
```

As long as you set the option `verbose=True` it will be printed it out initially. If you are looking for the source code, it can be found here:

https://github.com/RobertTLange/mle-logging/blob/192055b0a116f811aef8c5f4eb869aa563bd5f0b/mle_logging/comms.py#L53-L68

And if you want to print it out at intermediate steps (so after initialization), you could do the following (sorry, this was not meant to be printed after the startup of the log):

```python
from mle_logging.comms import print_startup
log = MLELogger(...)
print_startup(
                log.experiment_dir,
                log.config_copy,
                log.stats_log.time_to_track,
                log.stats_log.what_to_track,
                log.model_log.model_type,
                log.seed_id,
                log.use_tboard,
                False,
                log.print_every_k_updates,
                log.model_log.ckpt_time_to_track,
                log.model_log.save_every_k_ckpt,
                log.model_log.save_top_k_ckpt,
                log.model_log.top_k_metric_name,
                log.model_log.top_k_minimize_metric,
            )
```

Let me know if this helps or if there are any improvement suggestions you have. Rob

**Comment by tuttyfrutyee** [comment]
Okay thank you, I think that interface is pretty cool. Something like log.show() would be very handy I believe. It feels like htop
